### ISSUE TITLE
{"code":-97,"message":"ERROR_PROXY_AUTH_FAILED"}

### ISSUE THREAD

**Issue by lihongzhai** [tencentyun/cos-dotnet-sdk#6]
我克隆代码，修改代码中的AppID，SECRET_ID，SECRET_KEY和bucketName为我账户里的内容，其它未作任何修改
然后编译，运行，结果不断得到异常，不能连通服务器！

经过捕获内部异常为：
StatusCode	BadRequest	System.Net.HttpStatusCode

堆栈：
   在 System.Net.HttpWebRequest.GetResponse()
   在 QCloud.CosApi.Common.Request.SendRequest(String url, Dictionary`2& data, HttpMethod requestMethod, Dictionary`2& header, Int32 timeOut, String localPath, Int64 offset, Int32 sliceSize) 
位置 D:\MyProjects\2016\Scr\cos_test\cos_dotnet_sdk\Common\Request.cs:行号 124

控制台输出：
{"code":-97,"message":"ERROR_PROXY_AUTH_FAILED"}

整个过程唯一的可疑之处是我是用Net4.6框架编译的。难道这个SDK不支持Net4.6框架编译？求官方解答。

**Comment by ghost** [comment]
cos目前是分两个版本的，这里的是V3版本的SDK，看到您那边是用的V4版本，需要到使用cos-donet-sdk-v4
，然后看到在那边也提了一个issues，具体问题将在那一个里面回复。

**Comment by lihongzhai** [comment]
谢谢：）。建议在本项目说明里提一下这个是V3版的。
